=== bewest/data-model/schemas/diabetes/cbg.json
{
	"type":"object",
	"$schema": "http://json-schema.org/draft-03/schema",
	"id": "#/diabetes/cbg.json",
  "title": "continuous blood glucose (CBG)",
  "name": "cbg",
  "description": "Readings from a continuously monitoring device",
	"properties":{
		"deviceTime": {
			"type":"string",
			"id": "http://jsonschema.net/cbg/deviceTime",
			"required":true
		},
		"id": {
			"type":"string",
			"id": "http://jsonschema.net/cbg/id",
			"required":false
		},
		"type": {
			"type":"string",
			"id": "http://jsonschema.net/type/cbg",
			"required":true
		},
		"value": {
			"type":"number",
			"id": "http://jsonschema.net/cbg/value",
			"required":true
		}
	}
}

=== bewest/data-model/examples/list-smbgs.json
[
  {
      "deviceTime": "2014-02-04T04:46:08",
      "type": "smbg",
      "id": "eef2f145-5f63-4b80-b19b-94b3921cb3c1",
      "value": 149
  },
  {
      "deviceTime": "2014-02-04T04:46:08",
      "type": "smbg",
      "id": "eef2f145-5f63-4b80-b19b-94b3921cb3c1",
      "value": 149
  },
  {
      "deviceTime": "2014-02-04T04:46:08",
      "type": "smbg",
      "id": "eef2f145-5f63-4b80-b19b-94b3921cb3c1",
      "value": 149
  }
]

=== bewest/data-model/examples/three/cbg.json
[
  {
      "deviceTime": "2014-02-03T18:06:06",
      "type": "cbg",
      "id": "ba72e270-2d48-48c0-8f63-0ac2914fb759",
      "value": 77
  },
  {
      "deviceTime": "2014-02-03T18:06:06",
      "type": "cbg",
      "id": "ba72e270-2d48-48c0-8f63-0ac2914fb759",
      "value": 77
  },
  {
      "deviceTime": "2014-02-03T18:06:06",
      "type": "cbg",
      "id": "ba72e270-2d48-48c0-8f63-0ac2914fb759",
      "value": 77
  }
]
