=== bewest/data-model/schemas/diabetes/bolus/dual.json
{
	"type":"object",
	"$schema": "http://json-schema.org/draft-03/schema",
  "title": "Dual wave bolus",
  "additionalProperties": false,
	"properties":{
		"deviceTime": {
			"type":"string",
			"id": "http://jsonschema.net/deviceTime",
			"required":true
		},
		"duration": {
			"type":"number",
			"id": "http://jsonschema.net/duration",
			"required":true
		},
		"extendedDelivery": {
			"type":"number",
			"id": "http://jsonschema.net/extendedDelivery",
			"required":true
		},
		"extended": {
			"type":"boolean",
			"id": "http://jsonschema.net/extended",
			"required":true
		},
		"id": {
			"type":"string",
			"id": "http://jsonschema.net/id",
			"required":false
		},
		"initialDelivery": {
			"type":"number",
			"id": "http://jsonschema.net/initialDelivery",
			"required":true
		},
		"recommended": {
			"type":"number",
			"id": "http://jsonschema.net/recommended",
			"required":true
		},
		"type": {
			"enum": ["bolus", "bolus-dual"],
			"required":true
		},
		"value": {
			"type":"number",
			"id": "http://jsonschema.net/value",
			"required":true
		}
	}
}

=== bewest/data-model/examples/three/bolus.json
[
  {
      "initialDelivery": 2.9,
      "extendedDelivery": 2.8000000000000003,
      "value": 5.7,
      "recommended": 5.7,
      "deviceTime": "2014-02-04T04:49:08",
      "duration": 14400000,
      "extended": true,
      "type": "bolus",
      "id": "19bbfa82-7ee8-4f5c-a8c7-d3b9821aece3"
  },
  {
      "recommended": 5.7,
      "deviceTime": "2014-02-04T09:30:25",
      "type": "bolus",
      "id": "5182bbde-cc9a-475e-87fe-01b2149083ce",
      "value": 5.7
  },
  {
      "deviceTime": "2014-02-05T17:32:26",
      "value": 2.9,
      "recommended": 2.9,
      "extendedDelivery": 2.9,
      "duration": 3600000,
      "extended": true,
      "type": "bolus",
      "id": "0cb46cab-1d4e-4242-a173-75c5859e1d1b"
  }
]
