=== bewest/data-model/schemas/diabetes/basal/inferred.json
{
	"type":"object",
	"$schema": "http://json-schema.org/draft-03/schema",
	"id": "basal-inferred.json",
	"name": "basal-inferred",
	"title": "Inferred basal rate",
	"description": "Inferred basal rates moments in time for which we know the rate delivered, but the device did not keep an audit trail for that block of time.",
	"properties":{
		"delivered": {
			"type":"number",
			"id": "http://jsonschema.net/basal/inferred/delivered",
			"required":true
		},
		"deliveryType": {
			"type":"string",
			"id": "http://jsonschema.net/deliveryType",
			"required":true
		},
		"end": {
			"type":"string",
			"id": "http://jsonschema.net/end",
			"required":true
		},
		"id": {
			"type":"string",
			"id": "http://jsonschema.net/id",
			"required":false
		},
		"inferred": {
			"type":"boolean",
			"id": "http://jsonschema.net/inferred",
			"required":false
		},
		"start": {
			"type":"string",
			"id": "http://jsonschema.net/start",
			"required":true
		},
		"type": {
			"type":"string",
      "enum": [ "basal-rate-segment" ],
			"id": "http://jsonschema.net/basal/type",
			"required":true
		},
		"value": {
			"type":"number",
			"id": "http://jsonschema.net/basal/value",
			"required":true
		}
	}
}

=== bewest/data-model/examples/three/basals.json
[
  {
      "delivered": 1.0,
      "end": "2014-03-07T07:18:02",
      "deliveryType": "scheduled",
      "inferred": true,
      "value": 1.0,
      "start": "2014-03-07T06:00:00",
      "type": "basal-rate-segment",
      "id": "8490c2ea-ea91-4324-9a16-87582b2bab73"
  },
  {
      "delivered": 0.65,
      "end": "2014-03-07T04:00:00",
      "deliveryType": "scheduled",
      "inferred": false,
      "value": 0.65,
      "start": "2014-03-07T02:00:00",
      "type": "basal-rate-segment",
      "id": "893dedf8-1d10-45dd-99c9-b79dcd516f32"
  },
  {
      "delivered": 0.75,
      "end": "2014-03-07T06:08:07",
      "deliveryType": "temp",
      "inferred": false,
      "value": 0.75,
      "start": "2014-03-07T01:08:07",
      "type": "basal-rate-segment",
      "id": "ccae81b6-6fa8-4501-9559-b6c4b9f5afc3"
  }
]
